// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Zn_zfPM0qbPk8uazh0Gsl5-uG4NqZ4E',
    appId: '1:1012274783082:web:29559a580d05566b1cfb13',
    messagingSenderId: '1012274783082',
    projectId: 'shoppywell-7a2c3',
    authDomain: 'shoppywell-7a2c3.firebaseapp.com',
    storageBucket: 'shoppywell-7a2c3.firebasestorage.app',
    measurementId: 'G-02ZGHCGQYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdd6IBZOCgJ1wPsJ6Yk0z8PF5Jqey2xqA',
    appId: '1:1012274783082:android:8cfe1440e62c7ef31cfb13',
    messagingSenderId: '1012274783082',
    projectId: 'shoppywell-7a2c3',
    storageBucket: 'shoppywell-7a2c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCujPgn5_bTOZSwpyhX8DMdCz_tQeaboUM',
    appId: '1:1012274783082:ios:9f2a84a67092a1b51cfb13',
    messagingSenderId: '1012274783082',
    projectId: 'shoppywell-7a2c3',
    storageBucket: 'shoppywell-7a2c3.firebasestorage.app',
    iosBundleId: 'com.example.shopywell',
  );
}
